version: '3.9'

services:
  server:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '8787:8787'
    environment:
      - TRADECLASS_HOST=0.0.0.0
      - TRADECLASS_ONBOARDING_KEY=TradeClass-dev-onboarding

  room:
    build:
      context: .
      dockerfile: apps/room/Dockerfile
    ports:
      - '5173:5173'
    depends_on:
      - server
    environment:
      - SERVER_URL=http://server:8787
      - TRADECLASS_ONBOARDING_KEY=TradeClass-dev-onboarding
